algoritmo "Contagem (for - enquanto)"
// Função : O usuario vai definir um tempo e vamos começar uma contagem com o FOR
// Autor :
// Data : 24/08/2023
// Seção de Declarações 
var

   tempo: inteiro

inicio
// Seção de Comandos

   Escreva("Digite o tempo")
   leia(tempo)
   
              enquanto (tempo <= 10) faca
              
                       EscrevaL(tempo)
                       tempo <- tempo +1

                       
                       fimenquanto
fimalgoritmo
