algoritmo "primeiro"
var      msg: caractere     // == "msg recebe letras"

inicio

      msg <- "Ola, Mundo!"     // == msg recebe "Ola, mundo"
      Escreval(msg)            // aqui imprimo oque esta dentro da variavel msg
      escreval("Mensagem ", msg) // outra forma de digitar a mensagem tambem
      // escreva = imprimir algo na tela
      // escreval = escrever e pular linha
      Escreval("Me livrei da maldição")   // forma tambem de imprimir
fimalgoritmo
