algoritmo "semnome"
var
   nome: caractere // aqui estou dizendo que nome vai receber letras(strings)
   
inicio

      nome <- "Alleph" // caso eu nao queira perguntar ao usuario
                       // dessa forma eu ja to atribuindo na variavel nome
      escreva("Digite seu nome: ")
      leia(nome)
      escreval("Muito bem vindo ao meu programa ",nome)
      escreval("Oque posso fazer por você hoje ",nome," ?")
      

fimalgoritmo
