algoritmo "Vetores"
// Função :
// Autor :
// Data : 04/10/2023
// Seção de Declarações 
var
       dados: vetor[1..2] de caractere
       contagem : inteiro
inicio
// Seção de Comandos 
   Escreva("Digite seu nome: ")
   leia(dados[1])
   Escreva("Digite seu sobrenome: ")
   leia(dados[2])
   
   para contagem <- 1 ate 2 faca
          escreva(dados[contagem]) // aqui mando imprimir o dado1 e dado2
   fimpara
fimalgoritmo
